repos:
  - repo: https://github.com/psf/black
    rev:  19.10b0
    hooks:
      - id: black
  - repo: https://github.com/timothycrosley/isort
    rev:  4.3.21
    hooks:
      - id: isort
        args: [--check-only]
        additional_dependencies:
          - toml
  - repo: https://github.com/myint/docformatter
    rev:  v1.3.1
    hooks:
      - id: docformatter
        args: [--in-place, --wrap-summaries=80, --wrap-descriptions=72]
  - repo: https://github.com/pycqa/pylint
    rev: pylint-2.5.3
    hooks:
      - id: pylint
        additional_dependencies:
          - pyenchant~=3.1.1
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.780
    hooks:
      - id: mypy
        additional_dependencies:
          - tokenize-rt==3.2.0
  - repo: https://github.com/OliverSieweke/sphinx.git
    rev: 3.x
    hooks:
      - id: docs
        args: [-W, ./docs/source, ./docs/build]
        additional_dependencies:
          - sphinx_rtd_theme
        always_run: true
        files: ".^"
